### ISSUE TITLE
[BUG] Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'

### ISSUE THREAD

**Issue by slavanga** [microsoft/applicationinsights-react-js#32]
A type error similar to issue https://github.com/microsoft/ApplicationInsights-JS/issues/1324 has appeared in the latest versions:
`Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'.`

Versions:
- @microsoft/applicationinsights-react-js **v3.4.0**
- @microsoft/applicationinsights-web **v2.8.9**

Here's the simplified example from my next.js app:
```js
import { ReactPlugin } from '@microsoft/applicationinsights-react-js';
import {
  ApplicationInsights,
  ITelemetryPlugin,
} from '@microsoft/applicationinsights-web';

const appInsights = new ApplicationInsights({
  config: {
    connectionString: `InstrumentationKey=${process.env.AZURE_INSTURMENTATION_KEY};IngestionEndpoint=https://switzerlandnorth-0.in.applicationinsights.azure.com/;LiveEndpoint=https://switzerlandnorth.livediagnostics.monitor.azure.com/`,
    enableAutoRouteTracking: true,
    extensions: [new ReactPlugin()], // <- error happens here
  },
});
```

**Comment by MSNev** [comment]
I think #31 will fix resolve the type error which is cause (I believe) because of an optional change we made to a base interface.
The PR just bumps the expected base version of the React-JS plugin to the current version.

As we are planning to release 2.8.10 shortly (next week), there will be an additional bump to 2.8.10 before we release an updated version of this plugin (which should also be next week)

**Comment by jarosik10** [comment]
Hey, I solved this problem in a rather strange way.
1. Remove dependecies from package.json
```
   "@microsoft/applicationinsights-react-js": "3.4.1",
   "@microsoft/applicationinsights-web": "2.8.11",
```
2. Run `npm install`
3. Run `npm install @microsoft/applicationinsights-react-js` `npm install @microsoft/applicationinsights-web`

The operation of reintalling these packages changed my package.lock.json and the type problem has been magically solved. So it looks that package-lock.json was somehow corrupted?

**Comment by MSNev** [comment]
Just quickly looking (not upgrading / compiling) at the source code, In theory, if you "re-compile" the original source code (fixing any import issues -- which there should only be a couple of minor ones (importing from applicationinsights-common) it __should__ work.

**Comment by dashakrolik** [comment]
I have the same issue upgrading from 3.4.0 to 3.4.2. We use "react": "18.2.0". Tried reinstalling, recompiling and issue still peersists. Is it closed or are you working on a fix? I'm confused.

**Comment by MSNev** [comment]
Ok, after a little bit more research I (think) I might have identified a contributing issue which is causing this problem and setting your dependencies to match avoids.

Basically, as part of the `types` that we are generating and publishing in the packages we are using the api-extractor and with this we have it configured to "include" some of the other bundled packages within the type [like this](https://github.com/microsoft/ApplicationInsights-JS/blob/053a8a0718ffab764016b55bfb22ab2809e06a71/AISKU/api-extractor.json#L63-L70).

While this "generally" works it appears (at least when using Typescript 4.9.5) that if you include individual packages (like Core, common, etc) and even with the same package version that TypeScript sometimes considers the types/interfaces as "different" and will give this error -- even when they are basically type compatible.

I'll raise an issue with ApplicationInsights to remove the `bundledPackages` from all of the api-extractor.json files so that the next version (2.8.13 and 3.0.1 (hopefully)) won't contribute to this problem -- and (hopefully) it doesn't cause any other typing issues.

**Comment by MSNev** [comment]
https://github.com/microsoft/ApplicationInsights-JS/issues/2052

I'll reopen this issue until the above and a perhaps an updated version of this plugin is published

**Comment by dokunbam** [comment]
> I can confirm that down-grading to ApplicationInsights v2.8.12 has sorted the build errors:
> 
> ```
> "@microsoft/applicationinsights-react-js": "^3.4.2",
> "@microsoft/applicationinsights-web": "^2.8.12",
> ```

This fixed the issue for me

**Comment by sionjlewis** [comment]
This is not fixed for:
"@microsoft/applicationinsights-react-js": "^3.4.2",
"@microsoft/applicationinsights-web": "2.8.12",
...

**Comment by MSNev** [comment]
@sionjlewis can you check your local lock file the make sure that you are using 2.8.12... As 3.4.2 was built with 2.8.12 as it's dependency.
Also can you provide you tsconfig.json settings

We did release 2.8.13 this week which removes the bundled definitions in the types (see https://github.com/microsoft/ApplicationInsights-JS/issues/2052) and I am planning on release an update to this component to 2.8.13 (to *hopefully* avoid this issue for later releases -- and not have to release an update every time as that would effectively take us back to pinning the version which we don't want to do)

**Comment by ievgennaida** [comment]
> @sionjlewis can you check your local lock file the make sure that you are using 2.8.12... As 3.4.2 was built with 2.8.12 as it's dependency. Also can you provide you tsconfig.json settings
> 
> We did release 2.8.13 this week which removes the bundled definitions in the types (see [microsoft/ApplicationInsights-JS#2052](https://github.com/microsoft/ApplicationInsights-JS/issues/2052)) and I am planning on release an update to this component to 2.8.13 (to _hopefully_ avoid this issue for later releases -- and not have to release an update every time as that would effectively take us back to pinning the version which we don't want to do)

I am having the same exception for the:

```
"@microsoft/applicationinsights-react-js": "^3.4.2",
"@microsoft/applicationinsights-web": "2.8.12",
```

lock file definatelly has locked 2.8.12 and 3.4.2

```
	"node_modules/@microsoft/applicationinsights-web": {
			"version": "2.8.12",
```

**Comment by ievgennaida** [comment]
@MSNev 
Fixed when all 3 versions are frozen:
`	"@microsoft/applicationinsights-react-js": "3.4.2",
		"@microsoft/applicationinsights-web": "2.8.12",
		"@microsoft/applicationinsights-core-js":"2.8.12",`

**Comment by MSNev** [comment]
Got it.

We are about to release v3.4.3 which includes several fixes that will hopefully avoid this issue in the future. It includes
- Updated to v2.8.14 of Application Insights [which has some specific fixes for this error](https://github.com/microsoft/ApplicationInsights-JS/issues/2052)
- As part of preparing for updating to fully support ApplicationInsights 3.x we have moved 3.4.3 into a release3.x branch and we will be publishing an updated version where we are goign to bump the major version number to match the major version number of React-JS moving forward

**Comment by ChristopherCapito** [comment]
Well I have bad news. I just installed both packages while going through a Medium article related to using AppInsights with NextJS https://medium.com/@nirbhayluthra/integrating-azure-application-insights-with-next-js-the-easy-way-afc83596afad

    "@microsoft/applicationinsights-react-js": "^3.4.3",
    "@microsoft/applicationinsights-web": "^3.0.2",

Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'.
  Types of property 'setNextPlugin' are incompatible.

The code can be found in the Medium article as it is identical, except a custom type for the BrowserHistory.

``` typescript
type BrowserHistory = {
    url      : string;
    location : { pathname: string };
    listen   : () => void;
    state?   : { url: string };
};

```

**Comment by MSNev** [comment]
*sigh* - While we have not yet released version an ApplicationInsights compatible version of this plugin, v3.0.3 (of AI) has the same "set" of fixes so it should not be causing this specific issue.

**Comment by ChristopherCapito** [comment]
So the issue should hopefully resolve when v3.0.3 of AI releases? I do not need to implement this right away, so I probably have a week or two until this becomes an issue.

In any case, thank you for the quick answer :)

**Comment by MSNev** [comment]
Actually, just checked and the fixes were added in 3.0.2 of AI 😢, so because you are still seeing this means that the answer to above is no...

**Comment by MSNev** [comment]
@siyuniu-ms, As part of the work to upgrading to v3.x of AI (dynamic config support) can you try and repro this issue (v3.4.3 (react) with v3.0.2 (AI)) so that we can try to understand why the existing fixes have not addressed this (ongoing) problem.

**Comment by claudia-meneghesso** [comment]
Just tried the above (v3.4.3 (react) with v3.0.2 (AI)) and still getting the same issue 😫

**Comment by MSNev** [comment]
Can I assume that you don't have `skipLibCheck` set to `true`?

**Comment by siyuniu-ms** [comment]
Hi, I am currently working on enabling the dynamic config on PR #49, hope that could solve the problem.

**Comment by siyuniu-ms** [comment]
The issue should be solved by #49

**Comment by henrytoone** [comment]
It looks like the merge of #49 has caused a build error on main

**Comment by MSNev** [comment]
@siyuniu-ms can you please investigate.
@henrytoone What is the build error?

**Comment by henrytoone** [comment]
> @siyuniu-ms can you please investigate. @henrytoone What is the build error?

https://github.com/microsoft/applicationinsights-react-js/runs/14576935518
It looks like the nightly pipeline - I don't think I have sufficient permissions to view what it is that caused the error

**Comment by MSNev** [comment]
Yeh, I had a quick look and the nightly is failing.
As part of the nightly build, we automatically assign the build version as "nightly" with a build number and it's failing when the sample attempts to "resolve" this new name -- so it's probably an issue with our automated version updates.
@siyuniu-ms we can discuss later today.

**Comment by MSNev** [comment]
Ok, the above triggered a memory and I've just applied the same work-around we had to do for the CI pipeline. I've kicked off the nightly build job so it should produce something in the next hour or so -- we still need to "fix" the `setVersion` script though.

**Comment by MSNev** [comment]
😢 The "workaround" didn't work so needs more investigation

**Comment by LuwkasLima** [comment]
Not to cause too much spam, but facing the issue on NextJS FE:

/@microsoft/applicationinsights-react-js - v3.4.3
/@microsoft/applicationinsights-web - v3.0.1

tsconfig:

`{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "useUnknownInCatchVariables": false,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "types": ["vitest/globals"],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}`

**Comment by YairoR** [comment]
Hi, I'm facing the same issue. 

I'm using the following:
    "@microsoft/applicationinsights-react-js": "^3.4.3",
    "@microsoft/applicationinsights-web": "^3.0.2",

But getting the following error:
Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'.
  Types of property 'setNextPlugin' are incompatible.
    Type '(next: import("/.../node_modules/@microsoft/applicationinsights-react-js/node_modules/@microsoft/applicationinsights-core-js/types/JavaScriptSDK.Interfaces/ITelemetryPlugin").ITelemetryPlugin | import("/.../node_modules...' is not assignable to type '(next: import("/.../node_modules/@microsoft/applicationinsights-core-js/types/applicationinsights-core-js").ITelemetryPlugin | import("/.../node_modules/@microsoft/applicationinsights-core-js/types/applicationinsights-c...'.

**Comment by sarahannnicholson** [comment]
> > I can confirm that down-grading to ApplicationInsights v2.8.12 has sorted the build errors:
> > ```
> > "@microsoft/applicationinsights-react-js": "^3.4.2",
> > "@microsoft/applicationinsights-web": "^2.8.12",
> > ```
> 
> This fixed the issue for me

Unfortunately, doesn't work anymore with Typescript v5.0

**Comment by MSNev** [comment]
We should be releasing an updated version of this plugin (which will call v17 -- to align with the major version number of React) with full support for AI v3.x (which should (hopefully) resolve these specific issues -- although we have not performed any TS 5.x tests) -- probably by the end of next week (if not before)

**Comment by AbhayPrathap** [comment]
May i know is there any recent  update on this ?

**Comment by MSNev** [comment]
We are planning on creating these releases this week.

**Comment by GuiGimenez** [comment]
try
`extensions: [reactPlugin as any],`

**Comment by muchai-mercy** [comment]
Any updates on this issue and the releases for it? @MSNev @siyuniu-ms ?

**Comment by siyuniu-ms** [comment]
@muchai-mercy The issue is caused because we're using Application Insights JS as a dependency and there is some type conflicts caused by that. We'll wait until the AI JS v3.0.3 is updated, planned for next week. Once that update is done, this issue will be unblocked and fixed.

**Comment by siyuniu-ms** [comment]
fixed at #57

**Comment by jarosik10** [comment]
@siyuniu-ms I have applicationinsights-react-js": "17.0.3", applicationinsights-web": "3.0.7" and the issue still exists.

**Comment by daggmano** [comment]
Confirmed (broken) on @microsoft/applicationinsights-react-js: 17.0.3, @microsoft/applicationinsights-web: 3.0.8. Interestingly, I didn't get this with 17.0.3 / 3.0.7. Reverting back to 3.0.7 builds correctly. NGL, I hate these issues...

**Comment by siyuniu-ms** [comment]
Thanks @jarosik10 and @daggmano for bring it up. We are making a fix for it in our next release which I believe will help solve the problem from the root.

**Comment by p-hlp** [comment]
@siyuniu-ms @MSNev we received the updated from `3.1.0` to `3.1.1` and our builds/tests are failing with:

`TS2322: Type 'ReactPlugin' is not assignable to type 'ITelemetryPlugin'`

again. 

Works:
```json
    "@microsoft/applicationinsights-react-js": "17.1.0",
    "@microsoft/applicationinsights-web": "3.1.0",
```
Doesn't work:
```json
    "@microsoft/applicationinsights-react-js": "17.1.0",
    "@microsoft/applicationinsights-web": "3.1.1",
```

**Comment by siyuniu-ms** [comment]
Hi, thanks for the info.

We have not updated the React dependency on Application Insights to version 3.1.1, and that could be causing the type problem. The error should go away after we release version 17.1.1.

We are also working on solving the root cause of the problem. In the meantime, please continue using the same minor version to avoid the type error. Thanks.

**Comment by MSNev** [comment]
@siyuniu-ms can you please create the release updating this -- these are annoying as they are now always referencing the same packages (no longer embedding them). 

We will also need to investigate further, as these are purely TypeScript complaining, as functionally they are compatible.

**Comment by p-hlp** [comment]
> Hi, thanks for the info.
> 
> We have not updated the React dependency on Application Insights to version 3.1.1, and that could be causing the type problem. The error should go away after we release version 17.1.1.
> 
> We are also working on solving the root cause of the problem. In the meantime, please continue using the same minor version to avoid the type error. Thanks.

Appreciate the reply. Don't have an issue with waiting :). Was just a bit confused because the compatibility matrix says `17.1.0` is compatible with `^3.1.0`, so I'd expect `3.1.1` to work fine.

**Comment by siyuniu-ms** [comment]
@p-hlp Hi, 17.1.1 is now publish.

**Comment by RCSandberg** [comment]
For those finding this bug now...

https://microsoft.github.io/ApplicationInsights-JS/ExtensionErrorSteps
